---
kind: pipeline
name: default

steps:
- name: run tests
  image: alpine:latest
  commands:
  - apk add --no-cache bash python3 py3-pip
  - pip3 install --break-system-packages --no-cache-dir behave
  - python3 -m behave
  - ./features/teardown.sh
---
kind: signature
hmac: cc94542faa1deb9bef1b588874c60e6b744e258509dfb63187a0ca2317cd2e26

...
