---
kind: pipeline
name: default

steps:
- name: run tests
  image: alpine:latest
  commands:
  - apk add --no-cache bash python3
  - pip3 install --no-cache-dir behave
  - python3 -m behave
  - ./features/teardown.sh
---
kind: signature
hmac: 148cf11f80bcaa4cd311e0ccdf1babb55977761328d0763fbf4957c8873698d2

...
