---
- hosts: all
  remote_user: root
  tasks:
  - name: Install iptables
    apt: name=iptables
  - name: Install ipset
    apt: name=ipset
  - name: Copy systemd service
    copy:
      src:  ../etc/microfw.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: 0644
  - name: Copy microfw.sh
    copy:
      src:  ../src/microfw.sh
      dest: /usr/local/sbin/microfw
      owner: root
      group: root
      mode: 0755
  - name: mkdir /usr/local/lib/microfw
    file: path=/usr/local/lib/microfw/ state=directory
  - name: Copy generate_setup.py
    copy:
      src:  ../src/generate_setup.py
      dest: /usr/local/lib/microfw/generate_setup.py
      owner: root
      group: root
      mode: 0755
  - name: mkdir /etc/microfw
    file: path=/etc/microfw/ state=directory
  - name: Copy addresses
    copy:
      src:  "../nodes/{{ ansible_facts['hostname'] }}/addresses"
      dest: /etc/microfw/
      owner: root
      group: root
      mode: 0644
  - name: Copy services
    copy:
      src:  "../nodes/{{ ansible_facts['hostname'] }}/services"
      dest: /etc/microfw/
      owner: root
      group: root
      mode: 0644
  - name: Copy interfaces
    copy:
      src:  "../nodes/{{ ansible_facts['hostname'] }}/interfaces"
      dest: /etc/microfw/
      owner: root
      group: root
      mode: 0644
  - name: Copy rules
    copy:
      src:  "../nodes/{{ ansible_facts['hostname'] }}/rules"
      dest: /etc/microfw/
      owner: root
      group: root
      mode: 0644
  - name: Copy virtual
    copy:
      src:  "../nodes/{{ ansible_facts['hostname'] }}/virtual"
      dest: /etc/microfw/
      owner: root
      group: root
      mode: 0644
  - name: run compile
    command: microfw compile
  - name: Enable the systemd service
    systemd:
      name: microfw.service
      daemon_reload: yes
      enabled: yes
